### ISSUE TITLE
v0.3.1 release 👼

### ISSUE THREAD

**Issue by vdemeester** [docker/go-units#17]
We should tag the 0.3.1 release (and update vendoring in `docker/docker`)

/ping @calavera @thaJeztah @LK4D4

**Comment by thaJeztah** [comment]
SGTM, diff is small; https://github.com/docker/go-units/compare/v0.3.0...master

**Comment by vdemeester** [comment]
Ok, pushed `v0.3.1`, will update vendoring 👼
