### ISSUE TITLE
Release 0.5.0 (or 0.4.1)

### ISSUE THREAD

**Issue by kolyshkin** [docker/go-units#42]
Can we please merge https://github.com/docker/go-units/pull/36 and release v0.4.1 (or v.0.5.0)?

Commits since v0.4.0 (at the moment this is just PR #40): https://github.com/docker/go-units/compare/v0.4.0...master

**Comment by kolyshkin** [comment]
@thaJeztah PTAL (or do you think there is something else needed to be done for the next release? If yes, I am happy to help)

**Comment by thaJeztah** [comment]
I pushed v0.5.0 https://github.com/docker/go-units/releases/tag/v0.5.0
